#port
server:
  port: 8040
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

#database
spring:
  #  datasource:
  #    url:
  #    username:
  #    password:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #swagger spring version over 2.6
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: db
  mail:
    host: smtp.gmail.com
    port: 587
    username: dnwlswkd17@gmail.com
    password: tuwrypedvzbzbgfu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

#logging
logging:
  level:
    com.ssafy.kkini: debug
